// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/routegraph.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_proto_routegraph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_routegraph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{1}
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Zone          string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Shelter       bool                   `protobuf:"varint,6,opt,name=shelter,proto3" json:"shelter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_proto_routegraph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{2}
}

func (x *Stop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stop) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Stop) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Stop) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Stop) GetShelter() bool {
	if x != nil {
		return x.Shelter
	}
	return false
}

type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FrequencyMins int32                  `protobuf:"varint,4,opt,name=frequency_mins,json=frequencyMins,proto3" json:"frequency_mins,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_proto_routegraph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{3}
}

func (x *Line) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Line) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Line) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Line) GetFrequencyMins() int32 {
	if x != nil {
		return x.FrequencyMins
	}
	return 0
}

func (x *Line) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleUuid   string                 `protobuf:"bytes,1,opt,name=vehicle_uuid,json=vehicleUuid,proto3" json:"vehicle_uuid,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenTs    int64                  `protobuf:"varint,5,opt,name=last_seen_ts,json=lastSeenTs,proto3" json:"last_seen_ts,omitempty"`
	LastKnownLat  float64                `protobuf:"fixed64,6,opt,name=last_known_lat,json=lastKnownLat,proto3" json:"last_known_lat,omitempty"`
	LastKnownLon  float64                `protobuf:"fixed64,7,opt,name=last_known_lon,json=lastKnownLon,proto3" json:"last_known_lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_proto_routegraph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{4}
}

func (x *Vehicle) GetVehicleUuid() string {
	if x != nil {
		return x.VehicleUuid
	}
	return ""
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Vehicle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vehicle) GetLastSeenTs() int64 {
	if x != nil {
		return x.LastSeenTs
	}
	return 0
}

func (x *Vehicle) GetLastKnownLat() float64 {
	if x != nil {
		return x.LastKnownLat
	}
	return 0
}

func (x *Vehicle) GetLastKnownLon() float64 {
	if x != nil {
		return x.LastKnownLon
	}
	return 0
}

type Depot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Depot) Reset() {
	*x = Depot{}
	mi := &file_proto_routegraph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Depot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Depot) ProtoMessage() {}

func (x *Depot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Depot.ProtoReflect.Descriptor instead.
func (*Depot) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{5}
}

func (x *Depot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Depot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Depot) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Depot) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Depot) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// Edge messages
type NextEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	TravelTime    int32                  `protobuf:"varint,3,opt,name=travel_time,json=travelTime,proto3" json:"travel_time,omitempty"`
	Distance      int32                  `protobuf:"varint,4,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextEdge) Reset() {
	*x = NextEdge{}
	mi := &file_proto_routegraph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextEdge) ProtoMessage() {}

func (x *NextEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextEdge.ProtoReflect.Descriptor instead.
func (*NextEdge) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{6}
}

func (x *NextEdge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *NextEdge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *NextEdge) GetTravelTime() int32 {
	if x != nil {
		return x.TravelTime
	}
	return 0
}

func (x *NextEdge) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type ServesEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	StopId        string                 `protobuf:"bytes,2,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServesEdge) Reset() {
	*x = ServesEdge{}
	mi := &file_proto_routegraph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServesEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServesEdge) ProtoMessage() {}

func (x *ServesEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServesEdge.ProtoReflect.Descriptor instead.
func (*ServesEdge) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{7}
}

func (x *ServesEdge) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *ServesEdge) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *ServesEdge) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type AssignedTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleUuid   string                 `protobuf:"bytes,1,opt,name=vehicle_uuid,json=vehicleUuid,proto3" json:"vehicle_uuid,omitempty"`
	LineId        string                 `protobuf:"bytes,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedTo) Reset() {
	*x = AssignedTo{}
	mi := &file_proto_routegraph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedTo) ProtoMessage() {}

func (x *AssignedTo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedTo.ProtoReflect.Descriptor instead.
func (*AssignedTo) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{8}
}

func (x *AssignedTo) GetVehicleUuid() string {
	if x != nil {
		return x.VehicleUuid
	}
	return ""
}

func (x *AssignedTo) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *AssignedTo) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type ParkedAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleUuid   string                 `protobuf:"bytes,1,opt,name=vehicle_uuid,json=vehicleUuid,proto3" json:"vehicle_uuid,omitempty"`
	DepotId       string                 `protobuf:"bytes,2,opt,name=depot_id,json=depotId,proto3" json:"depot_id,omitempty"`
	Since         int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkedAt) Reset() {
	*x = ParkedAt{}
	mi := &file_proto_routegraph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkedAt) ProtoMessage() {}

func (x *ParkedAt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkedAt.ProtoReflect.Descriptor instead.
func (*ParkedAt) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{9}
}

func (x *ParkedAt) GetVehicleUuid() string {
	if x != nil {
		return x.VehicleUuid
	}
	return ""
}

func (x *ParkedAt) GetDepotId() string {
	if x != nil {
		return x.DepotId
	}
	return ""
}

func (x *ParkedAt) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// Complex RPC payloads
type AssignVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignVehicleRequest) Reset() {
	*x = AssignVehicleRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVehicleRequest) ProtoMessage() {}

func (x *AssignVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVehicleRequest.ProtoReflect.Descriptor instead.
func (*AssignVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{10}
}

func (x *AssignVehicleRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

type AssignVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	LineId        string                 `protobuf:"bytes,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignVehicleResponse) Reset() {
	*x = AssignVehicleResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVehicleResponse) ProtoMessage() {}

func (x *AssignVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVehicleResponse.ProtoReflect.Descriptor instead.
func (*AssignVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{11}
}

func (x *AssignVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *AssignVehicleResponse) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

type RecalibrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ObservedAvg   int32                  `protobuf:"varint,3,opt,name=observed_avg,json=observedAvg,proto3" json:"observed_avg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecalibrateRequest) Reset() {
	*x = RecalibrateRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecalibrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecalibrateRequest) ProtoMessage() {}

func (x *RecalibrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecalibrateRequest.ProtoReflect.Descriptor instead.
func (*RecalibrateRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{12}
}

func (x *RecalibrateRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *RecalibrateRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *RecalibrateRequest) GetObservedAvg() int32 {
	if x != nil {
		return x.ObservedAvg
	}
	return 0
}

type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartId       string                 `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	EndId         string                 `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	MaxHops       int32                  `protobuf:"varint,3,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{13}
}

func (x *PathRequest) GetStartId() string {
	if x != nil {
		return x.StartId
	}
	return ""
}

func (x *PathRequest) GetEndId() string {
	if x != nil {
		return x.EndId
	}
	return ""
}

func (x *PathRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Hops          int32                  `protobuf:"varint,2,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{14}
}

func (x *PathResponse) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *PathResponse) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

// Top pairs
type TopPairsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPairsRequest) Reset() {
	*x = TopPairsRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPairsRequest) ProtoMessage() {}

func (x *TopPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPairsRequest.ProtoReflect.Descriptor instead.
func (*TopPairsRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{15}
}

func (x *TopPairsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Lines         int32                  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_proto_routegraph_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{16}
}

func (x *Pair) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Pair) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Pair) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type TopPairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*Pair                `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPairsResponse) Reset() {
	*x = TopPairsResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPairsResponse) ProtoMessage() {}

func (x *TopPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPairsResponse.ProtoReflect.Descriptor instead.
func (*TopPairsResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{17}
}

func (x *TopPairsResponse) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// Depots idle stats
type DepotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepotsRequest) Reset() {
	*x = DepotsRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotsRequest) ProtoMessage() {}

func (x *DepotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotsRequest.ProtoReflect.Descriptor instead.
func (*DepotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{18}
}

func (x *DepotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DepotStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepotId       string                 `protobuf:"bytes,1,opt,name=depot_id,json=depotId,proto3" json:"depot_id,omitempty"`
	DepotName     string                 `protobuf:"bytes,2,opt,name=depot_name,json=depotName,proto3" json:"depot_name,omitempty"`
	ParkedCount   int32                  `protobuf:"varint,3,opt,name=parked_count,json=parkedCount,proto3" json:"parked_count,omitempty"`
	AvgIdleMs     float64                `protobuf:"fixed64,4,opt,name=avg_idle_ms,json=avgIdleMs,proto3" json:"avg_idle_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepotStat) Reset() {
	*x = DepotStat{}
	mi := &file_proto_routegraph_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotStat) ProtoMessage() {}

func (x *DepotStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotStat.ProtoReflect.Descriptor instead.
func (*DepotStat) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{19}
}

func (x *DepotStat) GetDepotId() string {
	if x != nil {
		return x.DepotId
	}
	return ""
}

func (x *DepotStat) GetDepotName() string {
	if x != nil {
		return x.DepotName
	}
	return ""
}

func (x *DepotStat) GetParkedCount() int32 {
	if x != nil {
		return x.ParkedCount
	}
	return 0
}

func (x *DepotStat) GetAvgIdleMs() float64 {
	if x != nil {
		return x.AvgIdleMs
	}
	return 0
}

type DepotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*DepotStat           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepotsResponse) Reset() {
	*x = DepotsResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotsResponse) ProtoMessage() {}

func (x *DepotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotsResponse.ProtoReflect.Descriptor instead.
func (*DepotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{20}
}

func (x *DepotsResponse) GetStats() []*DepotStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type NextListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopId        string                 `protobuf:"bytes,1,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextListRequest) Reset() {
	*x = NextListRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextListRequest) ProtoMessage() {}

func (x *NextListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextListRequest.ProtoReflect.Descriptor instead.
func (*NextListRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{21}
}

func (x *NextListRequest) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

type NextListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*NextEdge            `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextListResponse) Reset() {
	*x = NextListResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextListResponse) ProtoMessage() {}

func (x *NextListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextListResponse.ProtoReflect.Descriptor instead.
func (*NextListResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{22}
}

func (x *NextListResponse) GetEdges() []*NextEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ServesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServesListRequest) Reset() {
	*x = ServesListRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServesListRequest) ProtoMessage() {}

func (x *ServesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServesListRequest.ProtoReflect.Descriptor instead.
func (*ServesListRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{23}
}

func (x *ServesListRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

type ServesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*ServesEdge          `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServesListResponse) Reset() {
	*x = ServesListResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServesListResponse) ProtoMessage() {}

func (x *ServesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServesListResponse.ProtoReflect.Descriptor instead.
func (*ServesListResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{24}
}

func (x *ServesListResponse) GetEdges() []*ServesEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type AssignedListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleUuid   string                 `protobuf:"bytes,1,opt,name=vehicle_uuid,json=vehicleUuid,proto3" json:"vehicle_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedListRequest) Reset() {
	*x = AssignedListRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedListRequest) ProtoMessage() {}

func (x *AssignedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedListRequest.ProtoReflect.Descriptor instead.
func (*AssignedListRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{25}
}

func (x *AssignedListRequest) GetVehicleUuid() string {
	if x != nil {
		return x.VehicleUuid
	}
	return ""
}

type AssignedListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*AssignedTo          `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedListResponse) Reset() {
	*x = AssignedListResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedListResponse) ProtoMessage() {}

func (x *AssignedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedListResponse.ProtoReflect.Descriptor instead.
func (*AssignedListResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{26}
}

func (x *AssignedListResponse) GetAssignments() []*AssignedTo {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type ParkedListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepotId       string                 `protobuf:"bytes,1,opt,name=depot_id,json=depotId,proto3" json:"depot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkedListRequest) Reset() {
	*x = ParkedListRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkedListRequest) ProtoMessage() {}

func (x *ParkedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkedListRequest.ProtoReflect.Descriptor instead.
func (*ParkedListRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{27}
}

func (x *ParkedListRequest) GetDepotId() string {
	if x != nil {
		return x.DepotId
	}
	return ""
}

type ParkedListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parked        []*ParkedAt            `protobuf:"bytes,1,rep,name=parked,proto3" json:"parked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkedListResponse) Reset() {
	*x = ParkedListResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkedListResponse) ProtoMessage() {}

func (x *ParkedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkedListResponse.ProtoReflect.Descriptor instead.
func (*ParkedListResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{28}
}

func (x *ParkedListResponse) GetParked() []*ParkedAt {
	if x != nil {
		return x.Parked
	}
	return nil
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartId       string                 `protobuf:"bytes,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	EndId         string                 `protobuf:"bytes,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	MaxHops       int32                  `protobuf:"varint,3,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_proto_routegraph_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{29}
}

func (x *GenerateReportRequest) GetStartId() string {
	if x != nil {
		return x.StartId
	}
	return ""
}

func (x *GenerateReportRequest) GetEndId() string {
	if x != nil {
		return x.EndId
	}
	return ""
}

func (x *GenerateReportRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_proto_routegraph_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routegraph_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_routegraph_proto_rawDescGZIP(), []int{30}
}

func (x *GenerateReportResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *GenerateReportResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_proto_routegraph_proto protoreflect.FileDescriptor

const file_proto_routegraph_proto_rawDesc = "" +
	"\n" +
	"\x16proto/routegraph.proto\x12\n" +
	"routegraph\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty\"|\n" +
	"\x04Stop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12\x18\n" +
	"\ashelter\x18\x06 \x01(\bR\ashelter\"}\n" +
	"\x04Line\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12%\n" +
	"\x0efrequency_mins\x18\x04 \x01(\x05R\rfrequencyMins\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"\xde\x01\n" +
	"\aVehicle\x12!\n" +
	"\fvehicle_uuid\x18\x01 \x01(\tR\vvehicleUuid\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\flast_seen_ts\x18\x05 \x01(\x03R\n" +
	"lastSeenTs\x12$\n" +
	"\x0elast_known_lat\x18\x06 \x01(\x01R\flastKnownLat\x12$\n" +
	"\x0elast_known_lon\x18\a \x01(\x01R\flastKnownLon\"k\n" +
	"\x05Depot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\"u\n" +
	"\bNextEdge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1f\n" +
	"\vtravel_time\x18\x03 \x01(\x05R\n" +
	"travelTime\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x05R\bdistance\"T\n" +
	"\n" +
	"ServesEdge\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\x12\x17\n" +
	"\astop_id\x18\x02 \x01(\tR\x06stopId\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\"^\n" +
	"\n" +
	"AssignedTo\x12!\n" +
	"\fvehicle_uuid\x18\x01 \x01(\tR\vvehicleUuid\x12\x17\n" +
	"\aline_id\x18\x02 \x01(\tR\x06lineId\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\"^\n" +
	"\bParkedAt\x12!\n" +
	"\fvehicle_uuid\x18\x01 \x01(\tR\vvehicleUuid\x12\x19\n" +
	"\bdepot_id\x18\x02 \x01(\tR\adepotId\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\"/\n" +
	"\x14AssignVehicleRequest\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\"_\n" +
	"\x15AssignVehicleResponse\x12-\n" +
	"\avehicle\x18\x01 \x01(\v2\x13.routegraph.VehicleR\avehicle\x12\x17\n" +
	"\aline_id\x18\x02 \x01(\tR\x06lineId\"e\n" +
	"\x12RecalibrateRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12!\n" +
	"\fobserved_avg\x18\x03 \x01(\x05R\vobservedAvg\"Z\n" +
	"\vPathRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\tR\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\tR\x05endId\x12\x19\n" +
	"\bmax_hops\x18\x03 \x01(\x05R\amaxHops\"=\n" +
	"\fPathResponse\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\x12\x12\n" +
	"\x04hops\x18\x02 \x01(\x05R\x04hops\"'\n" +
	"\x0fTopPairsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"@\n" +
	"\x04Pair\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05lines\x18\x03 \x01(\x05R\x05lines\":\n" +
	"\x10TopPairsResponse\x12&\n" +
	"\x05pairs\x18\x01 \x03(\v2\x10.routegraph.PairR\x05pairs\"%\n" +
	"\rDepotsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x88\x01\n" +
	"\tDepotStat\x12\x19\n" +
	"\bdepot_id\x18\x01 \x01(\tR\adepotId\x12\x1d\n" +
	"\n" +
	"depot_name\x18\x02 \x01(\tR\tdepotName\x12!\n" +
	"\fparked_count\x18\x03 \x01(\x05R\vparkedCount\x12\x1e\n" +
	"\vavg_idle_ms\x18\x04 \x01(\x01R\tavgIdleMs\"=\n" +
	"\x0eDepotsResponse\x12+\n" +
	"\x05stats\x18\x01 \x03(\v2\x15.routegraph.DepotStatR\x05stats\"*\n" +
	"\x0fNextListRequest\x12\x17\n" +
	"\astop_id\x18\x01 \x01(\tR\x06stopId\">\n" +
	"\x10NextListResponse\x12*\n" +
	"\x05edges\x18\x01 \x03(\v2\x14.routegraph.NextEdgeR\x05edges\",\n" +
	"\x11ServesListRequest\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\"B\n" +
	"\x12ServesListResponse\x12,\n" +
	"\x05edges\x18\x01 \x03(\v2\x16.routegraph.ServesEdgeR\x05edges\"8\n" +
	"\x13AssignedListRequest\x12!\n" +
	"\fvehicle_uuid\x18\x01 \x01(\tR\vvehicleUuid\"P\n" +
	"\x14AssignedListResponse\x128\n" +
	"\vassignments\x18\x01 \x03(\v2\x16.routegraph.AssignedToR\vassignments\".\n" +
	"\x11ParkedListRequest\x12\x19\n" +
	"\bdepot_id\x18\x01 \x01(\tR\adepotId\"B\n" +
	"\x12ParkedListResponse\x12,\n" +
	"\x06parked\x18\x01 \x03(\v2\x14.routegraph.ParkedAtR\x06parked\"d\n" +
	"\x15GenerateReportRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\tR\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\tR\x05endId\x12\x19\n" +
	"\bmax_hops\x18\x03 \x01(\x05R\amaxHops\"N\n" +
	"\x16GenerateReportResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2\xf8\x11\n" +
	"\n" +
	"RouteGraph\x120\n" +
	"\n" +
	"CreateStop\x12\x10.routegraph.Stop\x1a\x10.routegraph.Stop\x12+\n" +
	"\aGetStop\x12\x0e.routegraph.ID\x1a\x10.routegraph.Stop\x120\n" +
	"\n" +
	"UpdateStop\x12\x10.routegraph.Stop\x1a\x10.routegraph.Stop\x12/\n" +
	"\n" +
	"DeleteStop\x12\x0e.routegraph.ID\x1a\x11.routegraph.Empty\x120\n" +
	"\n" +
	"CreateLine\x12\x10.routegraph.Line\x1a\x10.routegraph.Line\x12+\n" +
	"\aGetLine\x12\x0e.routegraph.ID\x1a\x10.routegraph.Line\x120\n" +
	"\n" +
	"UpdateLine\x12\x10.routegraph.Line\x1a\x10.routegraph.Line\x12/\n" +
	"\n" +
	"DeleteLine\x12\x0e.routegraph.ID\x1a\x11.routegraph.Empty\x129\n" +
	"\rCreateVehicle\x12\x13.routegraph.Vehicle\x1a\x13.routegraph.Vehicle\x121\n" +
	"\n" +
	"GetVehicle\x12\x0e.routegraph.ID\x1a\x13.routegraph.Vehicle\x129\n" +
	"\rUpdateVehicle\x12\x13.routegraph.Vehicle\x1a\x13.routegraph.Vehicle\x122\n" +
	"\rDeleteVehicle\x12\x0e.routegraph.ID\x1a\x11.routegraph.Empty\x123\n" +
	"\vCreateDepot\x12\x11.routegraph.Depot\x1a\x11.routegraph.Depot\x12-\n" +
	"\bGetDepot\x12\x0e.routegraph.ID\x1a\x11.routegraph.Depot\x123\n" +
	"\vUpdateDepot\x12\x11.routegraph.Depot\x1a\x11.routegraph.Depot\x120\n" +
	"\vDeleteDepot\x12\x0e.routegraph.ID\x1a\x11.routegraph.Empty\x129\n" +
	"\vGetNextEdge\x12\x14.routegraph.NextEdge\x1a\x14.routegraph.NextEdge\x12<\n" +
	"\x0eCreateNextEdge\x12\x14.routegraph.NextEdge\x1a\x14.routegraph.NextEdge\x12<\n" +
	"\x0eUpdateNextEdge\x12\x14.routegraph.NextEdge\x1a\x14.routegraph.NextEdge\x129\n" +
	"\x0eDeleteNextEdge\x12\x14.routegraph.NextEdge\x1a\x11.routegraph.Empty\x12?\n" +
	"\rGetServesEdge\x12\x16.routegraph.ServesEdge\x1a\x16.routegraph.ServesEdge\x12B\n" +
	"\x10CreateServesEdge\x12\x16.routegraph.ServesEdge\x1a\x16.routegraph.ServesEdge\x12B\n" +
	"\x10UpdateServesEdge\x12\x16.routegraph.ServesEdge\x1a\x16.routegraph.ServesEdge\x12=\n" +
	"\x10DeleteServesEdge\x12\x16.routegraph.ServesEdge\x1a\x11.routegraph.Empty\x12?\n" +
	"\rGetAssignedTo\x12\x16.routegraph.AssignedTo\x1a\x16.routegraph.AssignedTo\x12B\n" +
	"\x10CreateAssignedTo\x12\x16.routegraph.AssignedTo\x1a\x16.routegraph.AssignedTo\x12B\n" +
	"\x10UpdateAssignedTo\x12\x16.routegraph.AssignedTo\x1a\x16.routegraph.AssignedTo\x12=\n" +
	"\x10DeleteAssignedTo\x12\x16.routegraph.AssignedTo\x1a\x11.routegraph.Empty\x129\n" +
	"\vGetParkedAt\x12\x14.routegraph.ParkedAt\x1a\x14.routegraph.ParkedAt\x12<\n" +
	"\x0eCreateParkedAt\x12\x14.routegraph.ParkedAt\x1a\x14.routegraph.ParkedAt\x12<\n" +
	"\x0eUpdateParkedAt\x12\x14.routegraph.ParkedAt\x1a\x14.routegraph.ParkedAt\x129\n" +
	"\x0eDeleteParkedAt\x12\x14.routegraph.ParkedAt\x1a\x11.routegraph.Empty\x12T\n" +
	"\rAssignVehicle\x12 .routegraph.AssignVehicleRequest\x1a!.routegraph.AssignVehicleResponse\x12G\n" +
	"\x0fRecalibrateEdge\x12\x1e.routegraph.RecalibrateRequest\x1a\x14.routegraph.NextEdge\x12A\n" +
	"\fShortestPath\x12\x17.routegraph.PathRequest\x1a\x18.routegraph.PathResponse\x12E\n" +
	"\bTopPairs\x12\x1b.routegraph.TopPairsRequest\x1a\x1c.routegraph.TopPairsResponse\x12H\n" +
	"\x0fDepotsIdleStats\x12\x19.routegraph.DepotsRequest\x1a\x1a.routegraph.DepotsResponse\x12W\n" +
	"\x0eGenerateReport\x12!.routegraph.GenerateReportRequest\x1a\".routegraph.GenerateReportResponseB\x18Z\x16routegraph/proto;protob\x06proto3"

var (
	file_proto_routegraph_proto_rawDescOnce sync.Once
	file_proto_routegraph_proto_rawDescData []byte
)

func file_proto_routegraph_proto_rawDescGZIP() []byte {
	file_proto_routegraph_proto_rawDescOnce.Do(func() {
		file_proto_routegraph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_routegraph_proto_rawDesc), len(file_proto_routegraph_proto_rawDesc)))
	})
	return file_proto_routegraph_proto_rawDescData
}

var file_proto_routegraph_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_routegraph_proto_goTypes = []any{
	(*ID)(nil),                     // 0: routegraph.ID
	(*Empty)(nil),                  // 1: routegraph.Empty
	(*Stop)(nil),                   // 2: routegraph.Stop
	(*Line)(nil),                   // 3: routegraph.Line
	(*Vehicle)(nil),                // 4: routegraph.Vehicle
	(*Depot)(nil),                  // 5: routegraph.Depot
	(*NextEdge)(nil),               // 6: routegraph.NextEdge
	(*ServesEdge)(nil),             // 7: routegraph.ServesEdge
	(*AssignedTo)(nil),             // 8: routegraph.AssignedTo
	(*ParkedAt)(nil),               // 9: routegraph.ParkedAt
	(*AssignVehicleRequest)(nil),   // 10: routegraph.AssignVehicleRequest
	(*AssignVehicleResponse)(nil),  // 11: routegraph.AssignVehicleResponse
	(*RecalibrateRequest)(nil),     // 12: routegraph.RecalibrateRequest
	(*PathRequest)(nil),            // 13: routegraph.PathRequest
	(*PathResponse)(nil),           // 14: routegraph.PathResponse
	(*TopPairsRequest)(nil),        // 15: routegraph.TopPairsRequest
	(*Pair)(nil),                   // 16: routegraph.Pair
	(*TopPairsResponse)(nil),       // 17: routegraph.TopPairsResponse
	(*DepotsRequest)(nil),          // 18: routegraph.DepotsRequest
	(*DepotStat)(nil),              // 19: routegraph.DepotStat
	(*DepotsResponse)(nil),         // 20: routegraph.DepotsResponse
	(*NextListRequest)(nil),        // 21: routegraph.NextListRequest
	(*NextListResponse)(nil),       // 22: routegraph.NextListResponse
	(*ServesListRequest)(nil),      // 23: routegraph.ServesListRequest
	(*ServesListResponse)(nil),     // 24: routegraph.ServesListResponse
	(*AssignedListRequest)(nil),    // 25: routegraph.AssignedListRequest
	(*AssignedListResponse)(nil),   // 26: routegraph.AssignedListResponse
	(*ParkedListRequest)(nil),      // 27: routegraph.ParkedListRequest
	(*ParkedListResponse)(nil),     // 28: routegraph.ParkedListResponse
	(*GenerateReportRequest)(nil),  // 29: routegraph.GenerateReportRequest
	(*GenerateReportResponse)(nil), // 30: routegraph.GenerateReportResponse
}
var file_proto_routegraph_proto_depIdxs = []int32{
	4,  // 0: routegraph.AssignVehicleResponse.vehicle:type_name -> routegraph.Vehicle
	16, // 1: routegraph.TopPairsResponse.pairs:type_name -> routegraph.Pair
	19, // 2: routegraph.DepotsResponse.stats:type_name -> routegraph.DepotStat
	6,  // 3: routegraph.NextListResponse.edges:type_name -> routegraph.NextEdge
	7,  // 4: routegraph.ServesListResponse.edges:type_name -> routegraph.ServesEdge
	8,  // 5: routegraph.AssignedListResponse.assignments:type_name -> routegraph.AssignedTo
	9,  // 6: routegraph.ParkedListResponse.parked:type_name -> routegraph.ParkedAt
	2,  // 7: routegraph.RouteGraph.CreateStop:input_type -> routegraph.Stop
	0,  // 8: routegraph.RouteGraph.GetStop:input_type -> routegraph.ID
	2,  // 9: routegraph.RouteGraph.UpdateStop:input_type -> routegraph.Stop
	0,  // 10: routegraph.RouteGraph.DeleteStop:input_type -> routegraph.ID
	3,  // 11: routegraph.RouteGraph.CreateLine:input_type -> routegraph.Line
	0,  // 12: routegraph.RouteGraph.GetLine:input_type -> routegraph.ID
	3,  // 13: routegraph.RouteGraph.UpdateLine:input_type -> routegraph.Line
	0,  // 14: routegraph.RouteGraph.DeleteLine:input_type -> routegraph.ID
	4,  // 15: routegraph.RouteGraph.CreateVehicle:input_type -> routegraph.Vehicle
	0,  // 16: routegraph.RouteGraph.GetVehicle:input_type -> routegraph.ID
	4,  // 17: routegraph.RouteGraph.UpdateVehicle:input_type -> routegraph.Vehicle
	0,  // 18: routegraph.RouteGraph.DeleteVehicle:input_type -> routegraph.ID
	5,  // 19: routegraph.RouteGraph.CreateDepot:input_type -> routegraph.Depot
	0,  // 20: routegraph.RouteGraph.GetDepot:input_type -> routegraph.ID
	5,  // 21: routegraph.RouteGraph.UpdateDepot:input_type -> routegraph.Depot
	0,  // 22: routegraph.RouteGraph.DeleteDepot:input_type -> routegraph.ID
	6,  // 23: routegraph.RouteGraph.GetNextEdge:input_type -> routegraph.NextEdge
	6,  // 24: routegraph.RouteGraph.CreateNextEdge:input_type -> routegraph.NextEdge
	6,  // 25: routegraph.RouteGraph.UpdateNextEdge:input_type -> routegraph.NextEdge
	6,  // 26: routegraph.RouteGraph.DeleteNextEdge:input_type -> routegraph.NextEdge
	7,  // 27: routegraph.RouteGraph.GetServesEdge:input_type -> routegraph.ServesEdge
	7,  // 28: routegraph.RouteGraph.CreateServesEdge:input_type -> routegraph.ServesEdge
	7,  // 29: routegraph.RouteGraph.UpdateServesEdge:input_type -> routegraph.ServesEdge
	7,  // 30: routegraph.RouteGraph.DeleteServesEdge:input_type -> routegraph.ServesEdge
	8,  // 31: routegraph.RouteGraph.GetAssignedTo:input_type -> routegraph.AssignedTo
	8,  // 32: routegraph.RouteGraph.CreateAssignedTo:input_type -> routegraph.AssignedTo
	8,  // 33: routegraph.RouteGraph.UpdateAssignedTo:input_type -> routegraph.AssignedTo
	8,  // 34: routegraph.RouteGraph.DeleteAssignedTo:input_type -> routegraph.AssignedTo
	9,  // 35: routegraph.RouteGraph.GetParkedAt:input_type -> routegraph.ParkedAt
	9,  // 36: routegraph.RouteGraph.CreateParkedAt:input_type -> routegraph.ParkedAt
	9,  // 37: routegraph.RouteGraph.UpdateParkedAt:input_type -> routegraph.ParkedAt
	9,  // 38: routegraph.RouteGraph.DeleteParkedAt:input_type -> routegraph.ParkedAt
	10, // 39: routegraph.RouteGraph.AssignVehicle:input_type -> routegraph.AssignVehicleRequest
	12, // 40: routegraph.RouteGraph.RecalibrateEdge:input_type -> routegraph.RecalibrateRequest
	13, // 41: routegraph.RouteGraph.ShortestPath:input_type -> routegraph.PathRequest
	15, // 42: routegraph.RouteGraph.TopPairs:input_type -> routegraph.TopPairsRequest
	18, // 43: routegraph.RouteGraph.DepotsIdleStats:input_type -> routegraph.DepotsRequest
	29, // 44: routegraph.RouteGraph.GenerateReport:input_type -> routegraph.GenerateReportRequest
	2,  // 45: routegraph.RouteGraph.CreateStop:output_type -> routegraph.Stop
	2,  // 46: routegraph.RouteGraph.GetStop:output_type -> routegraph.Stop
	2,  // 47: routegraph.RouteGraph.UpdateStop:output_type -> routegraph.Stop
	1,  // 48: routegraph.RouteGraph.DeleteStop:output_type -> routegraph.Empty
	3,  // 49: routegraph.RouteGraph.CreateLine:output_type -> routegraph.Line
	3,  // 50: routegraph.RouteGraph.GetLine:output_type -> routegraph.Line
	3,  // 51: routegraph.RouteGraph.UpdateLine:output_type -> routegraph.Line
	1,  // 52: routegraph.RouteGraph.DeleteLine:output_type -> routegraph.Empty
	4,  // 53: routegraph.RouteGraph.CreateVehicle:output_type -> routegraph.Vehicle
	4,  // 54: routegraph.RouteGraph.GetVehicle:output_type -> routegraph.Vehicle
	4,  // 55: routegraph.RouteGraph.UpdateVehicle:output_type -> routegraph.Vehicle
	1,  // 56: routegraph.RouteGraph.DeleteVehicle:output_type -> routegraph.Empty
	5,  // 57: routegraph.RouteGraph.CreateDepot:output_type -> routegraph.Depot
	5,  // 58: routegraph.RouteGraph.GetDepot:output_type -> routegraph.Depot
	5,  // 59: routegraph.RouteGraph.UpdateDepot:output_type -> routegraph.Depot
	1,  // 60: routegraph.RouteGraph.DeleteDepot:output_type -> routegraph.Empty
	6,  // 61: routegraph.RouteGraph.GetNextEdge:output_type -> routegraph.NextEdge
	6,  // 62: routegraph.RouteGraph.CreateNextEdge:output_type -> routegraph.NextEdge
	6,  // 63: routegraph.RouteGraph.UpdateNextEdge:output_type -> routegraph.NextEdge
	1,  // 64: routegraph.RouteGraph.DeleteNextEdge:output_type -> routegraph.Empty
	7,  // 65: routegraph.RouteGraph.GetServesEdge:output_type -> routegraph.ServesEdge
	7,  // 66: routegraph.RouteGraph.CreateServesEdge:output_type -> routegraph.ServesEdge
	7,  // 67: routegraph.RouteGraph.UpdateServesEdge:output_type -> routegraph.ServesEdge
	1,  // 68: routegraph.RouteGraph.DeleteServesEdge:output_type -> routegraph.Empty
	8,  // 69: routegraph.RouteGraph.GetAssignedTo:output_type -> routegraph.AssignedTo
	8,  // 70: routegraph.RouteGraph.CreateAssignedTo:output_type -> routegraph.AssignedTo
	8,  // 71: routegraph.RouteGraph.UpdateAssignedTo:output_type -> routegraph.AssignedTo
	1,  // 72: routegraph.RouteGraph.DeleteAssignedTo:output_type -> routegraph.Empty
	9,  // 73: routegraph.RouteGraph.GetParkedAt:output_type -> routegraph.ParkedAt
	9,  // 74: routegraph.RouteGraph.CreateParkedAt:output_type -> routegraph.ParkedAt
	9,  // 75: routegraph.RouteGraph.UpdateParkedAt:output_type -> routegraph.ParkedAt
	1,  // 76: routegraph.RouteGraph.DeleteParkedAt:output_type -> routegraph.Empty
	11, // 77: routegraph.RouteGraph.AssignVehicle:output_type -> routegraph.AssignVehicleResponse
	6,  // 78: routegraph.RouteGraph.RecalibrateEdge:output_type -> routegraph.NextEdge
	14, // 79: routegraph.RouteGraph.ShortestPath:output_type -> routegraph.PathResponse
	17, // 80: routegraph.RouteGraph.TopPairs:output_type -> routegraph.TopPairsResponse
	20, // 81: routegraph.RouteGraph.DepotsIdleStats:output_type -> routegraph.DepotsResponse
	30, // 82: routegraph.RouteGraph.GenerateReport:output_type -> routegraph.GenerateReportResponse
	45, // [45:83] is the sub-list for method output_type
	7,  // [7:45] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_routegraph_proto_init() }
func file_proto_routegraph_proto_init() {
	if File_proto_routegraph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_routegraph_proto_rawDesc), len(file_proto_routegraph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_routegraph_proto_goTypes,
		DependencyIndexes: file_proto_routegraph_proto_depIdxs,
		MessageInfos:      file_proto_routegraph_proto_msgTypes,
	}.Build()
	File_proto_routegraph_proto = out.File
	file_proto_routegraph_proto_goTypes = nil
	file_proto_routegraph_proto_depIdxs = nil
}
